"""R-PERFECT Phase 3 #8 — auto-generate docs/env_manifest.md.

Walks the source tree and extracts every `os.getenv(...)` / `os.environ[...]`
reference, then writes a sorted markdown table:

  | env_var | default | criticality | files |

Heuristics:
  - if env name appears in a getenv with no default + no env hardcode →
    HARD_CRITICAL (bot crashes / feature offline)
  - if env name has a default value → SOFT_CRITICAL (feature has a fallback)
  - keys ending in _API_KEY / _TOKEN / _BEARER → API_KEY (rotate per §3)

Run: `python -m auto.generate_env_manifest > docs/env_manifest.md`
"""
from __future__ import annotations

import ast
import os
import re
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
SCAN_DIRS = ["bot.py", "modules", "auto", "morning_brief_scheduler.py",
             "scheduler_calendar_v2.py", "config.py", "commands_registry.py"]
EXCLUDE_DIRS = {"__pycache__", ".git", "tests", "node_modules"}

ENV_GETATTR_RE = re.compile(r"os\.getenv\(\s*['\"]([^'\"]+)['\"](\s*,\s*([^)]+))?\)")
ENV_BRACKET_RE = re.compile(r"os\.environ\[\s*['\"]([^'\"]+)['\"]\s*\]")


def _walk_files() -> Iterable[Path]:
    for entry in SCAN_DIRS:
        p = ROOT / entry
        if p.is_file() and p.suffix == ".py":
            yield p
        elif p.is_dir():
            for child in p.rglob("*.py"):
                if any(part in EXCLUDE_DIRS for part in child.parts):
                    continue
                yield child


def _criticality(name: str, has_default: bool) -> str:
    upper = name.upper()
    if upper.endswith("_API_KEY") or upper.endswith("_TOKEN") or upper.endswith("_BEARER") \
            or upper.endswith("_SECRET"):
        return "API_KEY"
    if has_default:
        return "SOFT_CRITICAL"
    return "HARD_CRITICAL"


def _extract_default(raw: str | None) -> str:
    if not raw:
        return "—"
    raw = raw.strip()
    if (raw.startswith("'") and raw.endswith("'")) or \
       (raw.startswith('"') and raw.endswith('"')):
        return raw[1:-1]
    return raw[:40]


def _signup_url(name: str) -> str:
    table = {
        "FRED_API_KEY":      "https://fred.stlouisfed.org/docs/api/api_key.html",
        "ARKHAM_API_KEY":    "https://www.arkhamintelligence.com/",
        "ETHERSCAN_API_KEY": "https://etherscan.io/myapikey",
        "DUNE_API_KEY":      "https://dune.com/settings/api",
        "L2BEAT_API_KEY":    "https://l2beat.com/api",
        "ARTEMIS_API_KEY":   "https://artemis.xyz/",
        "COINALYZE_API_KEY": "https://coinalyze.net/api/",
        "VELO_API_KEY":      "https://velodata.app/",
        "KALSHI_PRIVATE_KEY": "https://kalshi.com/help/api",
    }
    return table.get(name, "—")


def collect() -> dict[str, dict]:
    found: dict[str, dict] = {}
    for path in _walk_files():
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rel = path.relative_to(ROOT).as_posix()
        for m in ENV_GETATTR_RE.finditer(text):
            name = m.group(1)
            default = _extract_default(m.group(3))
            entry = found.setdefault(name, {
                "default": default if default != "—" else "",
                "files": set(), "has_default": default != "—",
            })
            entry["files"].add(rel)
            if default != "—" and not entry["default"]:
                entry["default"] = default
                entry["has_default"] = True
        for m in ENV_BRACKET_RE.finditer(text):
            name = m.group(1)
            entry = found.setdefault(name, {
                "default": "", "files": set(), "has_default": False,
            })
            entry["files"].add(rel)
    return found


def render(found: dict[str, dict]) -> str:
    lines = [
        "# Environment Manifest — pear-monitor-bot (private)",
        "",
        "_Auto-generated by `auto/generate_env_manifest.py`. Do not edit by hand —",
        "regenerate after adding any `os.getenv` or `os.environ[]` reference._",
        "",
        f"Total: **{len(found)} env vars** referenced across the codebase.",
        "",
        "| Env Var | Criticality | Default | Signup / docs |",
        "|---|---|---|---|",
    ]
    for name in sorted(found.keys()):
        info = found[name]
        crit = _criticality(name, info["has_default"])
        default = info["default"] or "—"
        if len(default) > 40:
            default = default[:37] + "..."
        url = _signup_url(name)
        lines.append(f"| `{name}` | {crit} | `{default}` | {url} |")
    lines.append("")
    lines.append("## Criticality legend")
    lines.append("")
    lines.append("- **HARD_CRITICAL** — no default; missing var = feature off / crash.")
    lines.append("- **SOFT_CRITICAL** — has a default; safe in dev, rotate in prod.")
    lines.append("- **API_KEY** — credential; rotate via runbook §3.")
    return "\n".join(lines)


if __name__ == "__main__":
    found = collect()
    out = render(found)
    out_path = ROOT / "docs" / "env_manifest.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path} with {len(found)} env vars", file=sys.stderr)
    sys.stdout.write(out)
